### PR TITLE
Skeletal Summary 2: Electric Boogaloo

### LINKED ISSUE #258: [Bug]: Into the Radius VR, no finger movement on index controllers
### Operating System

archlinux

### OpenXR Runtime

monado

### Describe the issue.

on index controllers, there is no finger movement/tracking. i didn't test for long
things look like they are working with OpenComposite

[xrizer_itr1.txt](https://github.com/user-attachments/files/24333766/xrizer_itr1.txt)

### Steps to reproduce

_No response_

### Please confirm you have reproduced this on the latest commit.

- [x] I have reproduced this on the latest commit

### PR DESCRIPTION
**Pull request by ImSapphire**
Rebased version of #69, containing some (slightly reworked) commits from #261.

Hand skeleton is cached, but the separate path for estimated summary is still there, since the bone transforms are in OpenVR coordinate space and it feels wrong converting them back...

Closes #258
Part of #251
Part of #256

### CODE REVIEW

File: src/input/skeletal.rs [hunk 1]
```diff
@@ -165,6 +162,115 @@ impl<C: openxr_data::Compositor> Input<C> {
...
+                4 => (
+                    joints[xr::HandJoint::LITTLE_METACARPAL],
+                    joints[xr::HandJoint::LITTLE_PROXIMAL],
+                    joints[xr::HandJoint::LITTLE_TIP],
+                ),
+                _ => unreachable!(),
+            };
+
+            let metacarpal_proximal_delta = metacarpal.translation - proximal.translation;
+            let tip_proxiimal_delta = tip.translation - proximal.translation;
```
Comment (Supreeeme) [inline src/input/skeletal.rs]:
```suggestion
            let tip_proximal_delta = tip.translation - proximal.translation;
```

File: src/input/skeletal.rs [hunk 2]
```diff
@@ -165,6 +162,115 @@ impl<C: openxr_data::Compositor> Input<C> {
...
+            let a = metacarpal_proximal_delta.length();
+            let b = tip_proxiimal_delta.length();
+
+            let curl = if a == 0.0 || b == 0.0 {
+                1.0
+            } else {
+                let ang_cos = (dot / (a * b)).clamp(-1.0, 1.0);
+                let ang = ang_cos.acos();
+
+                1.0 - (ang / PI)
```
Comment (Supreeeme) [inline src/input/skeletal.rs:275]: I'd appreciate some comments for what's going on here.

**Comment by prikhi** [comment]
Should fix #256, #251, #258, maybe more

File: src/input/skeletal.rs (hunk 2 above)
Comment (ImSapphire) [reply src/input/skeletal.rs:275]: added some comments

**Comment by prikhi** [comment]
Double checked since there's been a few pushes - can confirm that this still solves the Dungeons of Eternity gripping issue w/ Index Controllers.
