### PR TITLE
input: convert hand tracking data to model space if needed

### LINKED ISSUE #4: Model space skeletal bone data is incorrect
See comment in `input/skeletal.rs`. c331744ee41e741f70ad79bf96224748f4163edb

### PR DESCRIPTION
**Pull request by OrionMoonclaw**
fixes #4

So far I was only able to test this in Resonite and it works there, but Resonite doesn't make use of bone positions (for most of the bones anyway) and aux bones. HL:A crashes for me, so I'm unable to test it, but besides this it will require reference transforms to work correctly anyway.

### CODE REVIEW

File: src/input/skeletal.rs [hunk 1]
```diff
@@ -145,6 +139,19 @@ impl<C: openxr_data::Compositor> Input<C> {
         {
             xr_joint_to_vr_bone(&joints[joint], &mut transforms[bone as usize])
         }
+
+        // Convert back to model space if needed
+        // it is unnecessary to convert back and forth, but it works and it's easy
+        if space == vr::EVRSkeletalTransformSpace::Model {
+            let bone_data: Vec<(Vec3, Quat)> = parent_to_model_space_bone_data(
+                transforms.iter().map(|t| bone_transform_to_glam(*t))
+            ).collect();
```
Comment (Supreeeme) [inline src/input/skeletal.rs:148]: `collect` should be unnecessary here.

Comment (OrionMoonclaw) [reply src/input/skeletal.rs:148]: Borrow checker complains about it because the for loop borrows a mutable reference to transforms, which is still borrowed by the iterator here if the collect is removed :/

**Comment by Supreeeme** [comment]
Will merge after the conflict is fixed.
